apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nacos.fullname" . }}
  labels:
    app: {{ template "nacos.name" . }}
    chart: {{ template "nacos.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
data:
{{- if eq .Values.storage.type "mysql" }}
{{- if .Values.storage.external.enable }}
{{ toYaml .Values.storage.external | indent 2 | b64enc }}
{{- else }}
  mysqlHost: {{ printf "%s-mysql" (include "nacos.fullname" .) | b64enc | quote }}
  mysqlPort: {{ "3306" | b64enc }}
  mysqlDatabase: {{ .Values.mysql.db.name | b64enc | quote }}
  mysqlUser: {{ .Values.mysql.db.user | b64enc | quote }}
  mysqlPassword: {{ .Values.mysql.db.password | b64enc | quote }}
{{- end }}
{{- end }}
{{- if .Values.secret.enabled }}
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
